# spring:
#   datasource:
#     hikari:
#       maximum-pool-size: 10
#       minimum-idle: 5
#       idle-timeout: 300000        # 5분
#       connection-timeout: 20000   # 20초
#       max-lifetime: 1200000      # 20분
#       validation-timeout: 5000
#       connection-test-query: SELECT 1 FROM DUAL 